#!/bin/bash

display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ { getline; print }')
        record_type=$(echo "$result" | awk '{ print $4 }')
        destination=$(echo "$result" | awk '{ print $5 }')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

display_subdomain_info "$1" "$2"
